// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAGOpY2iz9mvA9FteAuz-UmlpBs2sxlQQI',
    appId: '1:911058134659:web:d5c1dbbe50544689181db6',
    messagingSenderId: '911058134659',
    projectId: 'fluttertmdb',
    authDomain: 'fluttertmdb.firebaseapp.com',
    storageBucket: 'fluttertmdb.appspot.com',
    measurementId: 'G-NSH80JZBQ1',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDDlQf0_E_A82A2TuZOi5t0Cu1dJ52br1I',
    appId: '1:911058134659:android:2075e87fb98ec8e6181db6',
    messagingSenderId: '911058134659',
    projectId: 'fluttertmdb',
    storageBucket: 'fluttertmdb.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyD_do6H4CCDiJaZc65u_tDwN8CoJhjbfuo',
    appId: '1:911058134659:ios:cf4e2cb24e08f844181db6',
    messagingSenderId: '911058134659',
    projectId: 'fluttertmdb',
    storageBucket: 'fluttertmdb.appspot.com',
    iosBundleId: 'com.adikmt.fluttertmdb',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyD_do6H4CCDiJaZc65u_tDwN8CoJhjbfuo',
    appId: '1:911058134659:ios:1e991f12166e4622181db6',
    messagingSenderId: '911058134659',
    projectId: 'fluttertmdb',
    storageBucket: 'fluttertmdb.appspot.com',
    iosBundleId: 'com.adikmt.fluttertmdb.RunnerTests',
  );
}
